config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  resources :events do
    get :join, to: 'events#join', as: 'join'
    get :accept_request, to: 'events#accept_request', as: 'accept_request'
    get :reject_request, to: 'events#reject_request', as: 'reject_request'

  end

  devise_for :users

  get 'tags/:tag', to: 'events#index', as: :tag

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  include Workflow
    workflow_column :state

  belongs_to :event
  belongs_to :user

  workflow do
    state :request_sent do
      event :accept, :transitions_to => :accepted
      event :reject , :transitions_to => :rejected
    end
    state :accepted
    state :rejected
  end

  def self.join_event(user_id, event_id, state)
    self.create(user_id: user_id, event_id: event_id, state: state)
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged
  belongs_to :organizers, class_name: "User"
  has_many :taggings
  has_many :tags, through: :taggings

  def self.pending_requests(event_id)
    Attendance.where(event_id: event_id, state: 'request_sent')
  end

  def slug_candidates
    [
      :title,
      [:title, :location],
    ]
  end

  def self.event_owner(organizer_id)
    User.find_by id: organizer_id
  end

  def all_tags=(names)
    self.tags = names.split(',').map do |t|
      Tag.where(name: t.strip).first_or_create!
    end
  end

  def all_tags
    tags.map(&:name).join(", ")
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).events
  end

  def self.tag_counts
    Tag.select("tags.name, count(taggings.tag_id) as count").
    joins(:taggings).group("taggings.tag_id")
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :events, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :organized_events, class_name: "Event", foreign_key: "organizer_id"
  has_many :attendances
  has_many :users, :through => :attendances
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :event_owner!, only: [:edit, :update, :destroy]
  before_action :set_event, only: [:show, :edit, :update, :destroy, :accept_request, :reject_request]

  def accept_request
    @attendance = Attendance.find_by(id: params[:attendance_id]) rescue nil
    @attendance.accept!
    'Applicant Accepted' if @attendance.save
    respond_with(@attendance)
  end

  def reject_request
    @attendance = Attendance.where(params[:attendance_id]) rescue nil
    @attendance.reject!
    'Applicant Rejected' if @attendance.save
    respond_with(@attendance)
  end

  def join
    @attendance = Attendance.join_event(current_user.id,
      params[:event_id], 'request_sent')
      'Request Sent' if @attendance.save
      respond_with @attendance
  end

  # GET /events
  # GET /events.json
  def index
    if params[:tag]
      @events = Event.tagged_with(params[:tag])
    else
      @events = Event.all
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event_owners = @event.organizers
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.organized_events.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def event_owner!
      authenticate_user!
      if @event
        if @event.organizer_id != current_user.id
          redirect_to events_path
          flash[:notice] = 'permission denied'
        end
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.where(slug: params[:id]).take
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :start_date, :end_date,
        :location, :agenda, :address, :organizer_id, :all_tags, :slug)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size - 1)
      yield(tag, classes[index.round])
    end
  end

  def avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png"
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :location %><br>
    <%= f.text_field :location, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :agenda %><br>
    <%= f.text_area :agenda, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_area :address, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :organizer_id %><br>
    <%= f.number_field :organizer_id, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :all_tags, "List All Tags, separate each tag by a comma" %><br/>
    <%= f.text_field :all_tags, :class => "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit :class => "btn btn-primary"%>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice" class="alert"><%= notice %></p>

<h1>Events</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Location</th>
      <th>Agenda</th>
      <th>Address</th>
      <th>Organizer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= l event.start_date, :format => :date_format %></td>
        <td><%= l event.end_date, :format => :date_format%></td>
        <td><%= event.location %></td>
        <td><%= event.agenda %></td>
        <td><%= event.address %></td>
        <td><%= event.organizer_id %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Tags</h3>
<div>
  <% tag_cloud Event.tag_counts, %w{css1 css2 css3 css4} do |tag, css_class| %>
  <%= link_to tag.name, tag_path(tag.name ), class: css_class %>
  <% end %>
</div>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>Create an Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @event.end_date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Agenda:</strong>
  <%= @event.agenda %>
</p>

<p>
  <strong>Address:</strong>
  <%= @event.address %>
</p>

<p>
  <strong>Organizers:</strong>
  <% if @event_owners %>
    <% @event_owners.each do |event_owner| %>
    <%= image_tag avatar_url(event_owner) %>
    <%= event_owner.email %>
    <br/>
    <% end %>
  <% end %>
</p>

<% if user_signed_in? && @event.organizer_id == current_user.id%>
  <label>Join Requests</label>
  <% if @pending_requests.present? %>
    <% @pending_requests.each do |p| %>
      <%= image_tag avatar_url(p.user) %>
      <%= p.user.email %>
        <%= link_to 'Accept',
          event_accept_request_path(:event_id => @event.id,
            :attendance_id => p.id), :class => "btn btn-success btn-sm"  %>
        <%= link_to 'Reject',
          event_reject_request_path(:event_id => @event.id,
            :attendance_id => p.id), :class => "btn btn-danger btn-sm" %>
    <% end %>
  <% else %>
    <p> No Pending Requests for this event</p>
  <% end %>
<% end %>

<p>
  <strong>Tags:</strong>
  <%= @event.all_tags %>
</p>

<%= link_to "Join",
  event_join_path(:event_id => @event.id), :class => "btn btn-success btn-sm" %>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eventer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li class="active">
            <%= link_to "Events", events_path %>
          </li>
          <li>
            <a href="#">My Events</a>
          </li>
        </ul>
        <ul class="nav navbar-nav pull-right">
          <% if user_signed_in? %>
          <li><%= link_to "#{current_user.email}" %></li>
          <li class="active"><%= link_to "Logout", destroy_user_session_path%></li>
          <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li class="active"><%= link_to "Sign Up", new_user_registration_path%></li>
          <% end %>
        </ul>
      </div>
    </div>
  </header>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>